language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
before_script:
- git config --global user.name "Teracy Bot"
- git config --global user.email "teracy.com@gmail.com"
- export REPO_URL_GITHUB="https://$GH_TOKEN@github.com/$GH_REPO.git"
- . ./.travis/setup.sh
- echo $DEPLOY_HTML_DIR
script:
- make test
after_script:
- sudo pip install -r docs/requirements.txt --use-mirrors
- cd docs
- make setup_gh_pages
- make generate
- make deploy
after_success:
- coveralls
- make check-style
notifications:
  slack:
    on_success: change
    secure: CkrarcR2syf+Eu9TbVX7Hdnz++/OzV8TrPxX01Ok6lIz45ItjFby3HohdGiv/LdqAF91qP6cHzoADByoAAIDyExjsfJimMDtLfX6ZWAq8/WBS0g8bqpBv7s0ydPNB51DgzJNRh7adVExT3dhqO4XKcKmgL5UIOTLcouopB/cCn6/p6/B4l9I7AccHPRcPfsxgQnyUQPjpe2tyg/kpr0OHn+jdsiv0aTF9vmC1hSr/h3vTNDjp10jwW8XLaZIYUvATmwwXbADDB4DOAuVHtBV92bmDSwyZiBV7hqU9mqqVSdkDoHp/6nGBtJpsgaGEvPESCm2LdJrvfJNg+goYrmbaIr07kuISvbEjQxTX2MPsxTJy0Qmre9Ki6yXlJ/rSxAo2G6FMAUiqpKVV86L3g9Sway7Ovp5ihlZoJGMcA79y8WYAuSDN6PjY9GVksXiWr0cKFzBf/sBRTS4Zn60JLJSDA57KPny6DITN0WrMQFzc0hVVLINRjUhR4Nwn8P1TZVMGN+LRCOGj1/8MTgiZA9JaQbhjoWng+1M5f7BE9NKgOVVXn1+F2EI+ik+tiMpFfyinUPdgHS3SnVkd7Ja7dI1YG4MuJiCqS5WnEGXCu0xCOKbM2JyUtfnsw/IgsLnZ52G9+eI9W8Qq0GQ8S95Z4qsniZo49tU9g5bSKiN5rKiUSY=
env:
  global:
  - GH_REPO="teracyhq/flask-classy"
  - secure: WP/pK+Hcm7s3992sy6atnm+znXal6ZipVe4GIv90E71CqxhUG/dv6h+C4V4w48LEbDuW19tt6y5EOUeyoBl1bIAaIruBgJAyvQsi8PO6rAhnqQmfkPTnjfoOjHuWXO8dyFrQFhl9R2P/BxSmrYb/HFVhrjMHqwe0JnfSpwyDqjVN1xFYkg81fCjXnQA60uCY8TNPSnwkUb1w1vKG7Aot46uMJk1aWUmWFlDRBfQaqhw2y2KK/G4xB0t9UL4lRl66xER4iXjkYuGQEAik5OVKnpPf9IZRUDMUdPCdxzsbbw6qdrNls5FhvNhfz/PN+65l3Ui3eRQZs74Yw2eOI77pUUQ/6oYdbwm346cyrS33GiHWwvylQHsKdTIGf2C4AlyUAYzOIMmuNHaKuWSgt++czxEQQKfoNRp7Zthru0PuPS0Y9M3G2AsbiX05XpNL+qbhvnRzE/TYiTUoqKpB9TrTDF5FX6wLsgluHxroU27Tu2i5iB+DkNDeDCv1oZFnY3VZQd5rH8hu5BA6r5SWfe4VrUoTXABNAniCWvVZLu+zfY/kYcbd/RY8Tcm914I2TDU3tZa0rPjZl90y5NjoNJyu4+3mO3xUg/1fOWsTmdSW3EsLC0VqzJeSJTi9xX6zy62twcvGxivlgW2fippEZ6azboHJQHAjKS2PyUn//+MFRzk=
