version: '3'

services:

  dev:
    image: ${DEV_IMAGE:-python:3.8}
    working_dir: /opt/app
    command: sh run-dev.sh
    environment:
      REQUIREMENTS: ${REQUIREMENTS:-flask==2.0.0}
      CHECK_STYLE: ${CHECK_STYLE:-yes}
      RUN_TEST: ${RUN_TEST:-yes}
    volumes:
      - .:/opt/app


  docs-gen:
    image: python:3.8
    working_dir: /opt/app/docs
    command: >
      bash -c "pip install -r requirements.txt
      && make generate"
    volumes:
      - .:/opt/app
